'use client';

import { useCallback, useEffect, useState } from 'react';

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:6060';

interface CaptchaProps {
  /** Reports the current signed token + the user's answer to the parent form. */
  onChange: (token: string, answer: string) => void;
  /** Increment to force a fresh challenge (e.g. after a failed submit). */
  reloadSignal?: number;
}

/**
 * Fetches a server-generated arithmetic CAPTCHA and renders the challenge SVG.
 * The answer never leaves the browser except as a value checked server-side
 * against the signed token, so the client cannot bypass it.
 */
export default function Captcha({ onChange, reloadSignal = 0 }: CaptchaProps) {
  const [svg, setSvg] = useState('');
  const [token, setToken] = useState('');
  const [answer, setAnswer] = useState('');

  const load = useCallback(async () => {
    setAnswer('');
    const res = await fetch(`${API_URL}/api/auth/captcha`, { credentials: 'include' });
    const data = await res.json().catch(() => ({}));
    setSvg(data.svg || '');
    setToken(data.captchaToken || '');
    onChange(data.captchaToken || '', '');
  }, [onChange]);

  useEffect(() => {
    load();
  }, [load, reloadSignal]);

  return (
    <div style={{ marginTop: 8 }}>
      <label htmlFor="captcha">Solve the challenge</label>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
        {/* SVG is generated by our own API, not user input. */}
        <span
          aria-hidden="true"
          style={{ border: '1px solid #cbd5e1', borderRadius: 6, lineHeight: 0 }}
          dangerouslySetInnerHTML={{ __html: svg }}
        />
        <button
          type="button"
          className="btn-secondary"
          onClick={load}
          aria-label="Get a new challenge"
          style={{ padding: '4px 10px' }}
        >
          ↻
        </button>
      </div>
      <input
        id="captcha"
        inputMode="numeric"
        autoComplete="off"
        value={answer}
        onChange={(e) => {
          const v = e.target.value.replace(/\D/g, '');
          setAnswer(v);
          onChange(token, v);
        }}
        placeholder="Your answer"
        required
      />
    </div>
  );
}
